### ISSUE TITLE
Add `linkchecker` pre-commit hook configuration

### ISSUE THREAD

**Issue by d33bs** [linkchecker/linkchecker#772]
## Summary

Thanks for the great effort on this project, it's been helpful!

This is a feature request to add a pre-commit hook configuration for `linkchecker`. Pre-commit provides the [capability for custom hooks](https://pre-commit.com/#creating-new-hooks) which may be used by others. Often, projects which provide the capability to perform checks will have a `.pre-commit-hooks.yaml` file. This provides a certain level of trust and development alignment (see [Black's `.pre-commit-hooks.yaml`](https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml) as an example).

## Steps to develop and use

I think a `.pre-commit-hooks.yaml` file could be added with something like the following to enable this functionality:

```yaml
- id: linkchecker
  name: linkchecker
  description: "Check for broken links in web sites."
  entry: linkchecker
  language: python
  # additional defaults?
```

Usage outside of this for others would entail configuring their `.pre-commit-config.yaml` with something like:

```yaml
repos:
  - repo: https://github.com/linkchecker/linkchecker
    rev: vx.x.x
    hooks:
      - id: linkchecker
      # optional config below...
```
